// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbxgxydqyvsnnttmrbax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpieGd4eWRxeXZzbm50dG1yYmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzA3OTYsImV4cCI6MjA2NzE0Njc5Nn0.F5VhsRFYuhaUs_0N9Dt6mzKxNDzCYzYTT5A1OswL8c4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});